# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oce', models.IntegerField(default=0)),
                ('sin', models.IntegerField(default=0)),
            ],
        ),
    ]
